-- Start a transaction block
BEGIN;

-- Disable all foreign key constraints
SET CONSTRAINTS ALL DEFERRED;

-- Execute your operation (TRUNCATE, DELETE, etc.)
TRUNCATE TABLE public."Country";
TRUNCATE TABLE public."StudyLevel";

-- Re-enable all foreign key constraints
SET CONSTRAINTS ALL IMMEDIATE;

-- Commit the transaction
COMMIT;

INSERT INTO public."Country" (id, name, tag) VALUES
(1, 'Afghanistan', 'AFG'),
(2, 'Albania', 'ALB'),
(3, 'Algeria', 'DZA'),
(4, 'Andorra', 'AND'),
(5, 'Angola', 'AGO'),
(6, 'Antigua and Barbuda', 'ATG'),
(7, 'Argentina', 'ARG'),
(8, 'Armenia', 'ARM'),
(9, 'Australia', 'AUS'),
(10, 'Austria', 'AUT'),
(11, 'Azerbaijan', 'AZE'),
(12, 'The Bahamas', 'BHS'),
(13, 'Bahrain', 'BHR'),
(14, 'Bangladesh', 'BGD'),
(15, 'Barbados', 'BRB'),
(16, 'Belarus', 'BLR'),
(17, 'Belgium', 'BEL'),
(18, 'Belize', 'BLZ'),
(19, 'Benin', 'BEN'),
(20, 'Bhutan', 'BTN'),
(21, 'Bolivia', 'BOL'),
(22, 'Bosnia and Herzegovina', 'BIH'),
(23, 'Botswana', 'BWA'),
(24, 'Brazil', 'BRA'),
(25, 'Brunei', 'BRN'),
(26, 'Bulgaria', 'BGR'),
(27, 'Burkina Faso', 'BFA'),
(28, 'Burundi', 'BDI'),
(29, 'Cabo Verde', 'CPV'),
(30, 'Cambodia', 'KHM'),
(31, 'Cameroon', 'CMR'),
(32, 'Canada', 'CAN'),
(33, 'Central African Republic', 'CAF'),
(34, 'Chad', 'TCD'),
(35, 'Chile', 'CHL'),
(36, 'China', 'CHN'),
(37, 'Colombia', 'COL'),
(38, 'Comoros', 'COM'),
(39, 'Congo, Democratic Republic of the', 'COD'),
(40, 'Congo, Republic of the', 'COG'),
(41, 'Costa Rica', 'CRI'),
(42, 'Cote dIvoire', 'CIV'),
(43, 'Croatia', 'HRV'),
(44, 'Cuba', 'CUB'),
(45, 'Cyprus', 'CYP'),
(46, 'Czech Republic', 'CZE'),
(47, 'Denmark', 'DNK'),
(48, 'Djibouti', 'DJI'),
(49, 'Dominica', 'DMA'),
(50, 'Dominican Republic', 'DOM'),
(51, 'East Timor (Timor-Leste)', 'TLS'),
(52, 'Ecuador', 'ECU'),
(53, 'Egypt', 'EGY'),
(54, 'El Salvador', 'SLV'),
(55, 'Equatorial Guinea', 'GNQ'),
(56, 'Eritrea', 'ERI'),
(57, 'Estonia', 'EST'),
(58, 'Eswatini', 'SWZ'),
(59, 'Ethiopia', 'ETH'),
(60, 'Fiji', 'FJI'),
(61, 'Finland', 'FIN'),
(62, 'France', 'FRA'),
(63, 'Gabon', 'GAB'),
(64, 'The Gambia', 'GMB'),
(65, 'Georgia', 'GEO'),
(66, 'Germany', 'DEU'),
(67, 'Ghana', 'GHA'),
(68, 'Greece', 'GRC'),
(69, 'Grenada', 'GRD'),
(70, 'Guatemala', 'GTM'),
(71, 'Guinea', 'GIN'),
(72, 'Guinea-Bissau', 'GNB'),
(73, 'Guyana', 'GUY'),
(74, 'Haiti', 'HTI'),
(75, 'Honduras', 'HND'),
(76, 'Hungary', 'HUN'),
(77, 'Iceland', 'ISL'),
(78, 'India', 'IND'),
(79, 'Indonesia', 'IDN'),
(80, 'Iran', 'IRN'),
(81, 'Iraq', 'IRQ'),
(82, 'Ireland', 'IRL'),
(83, 'Israel', 'ISR'),
(84, 'Italy', 'ITA'),
(85, 'Jamaica', 'JAM'),
(86, 'Japan', 'JPN'),
(87, 'Jordan', 'JOR'),
(88, 'Kazakhstan', 'KAZ'),
(89, 'Kenya', 'KEN'),
(90, 'Kiribati', 'KIR'),
(91, 'Korea, North', 'PRK'),
(92, 'Korea, South', 'KOR'),
(93, 'Kosovo', 'XKX'),
(94, 'Kuwait', 'KWT'),
(95, 'Kyrgyzstan', 'KGZ'),
(96, 'Laos', 'LAO'),
(97, 'Latvia', 'LVA'),
(98, 'Lebanon', 'LBN'),
(99, 'Lesotho', 'LSO'),
(100, 'Liberia', 'LBR'),
(101, 'Libya', 'LBY'),
(102, 'Liechtenstein', 'LIE'),
(103, 'Lithuania', 'LTU'),
(104, 'Luxembourg', 'LUX'),
(105, 'Madagascar', 'MDG'),
(106, 'Malawi', 'MWI'),
(107, 'Malaysia', 'MYS'),
(108, 'Maldives', 'MDV'),
(109, 'Mali', 'MLI'),
(110, 'Malta', 'MLT'),
(111, 'Marshall Islands', 'MHL'),
(112, 'Mauritania', 'MRT'),
(113, 'Mauritius', 'MUS'),
(114, 'Mexico', 'MEX'),
(115, 'Micronesia, Federated States of', 'FSM'),
(116, 'Moldova', 'MDA'),
(117, 'Monaco', 'MCO'),
(118, 'Mongolia', 'MNG'),
(119, 'Montenegro', 'MNE'),
(120, 'Morocco', 'MAR'),
(121, 'Mozambique', 'MOZ'),
(122, 'Myanmar (Burma)', 'MMR'),
(123, 'Namibia', 'NAM'),
(124, 'Nauru', 'NRU'),
(125, 'Nepal', 'NPL'),
(126, 'Netherlands', 'NLD'),
(127, 'New Zealand', 'NZL'),
(128, 'Nicaragua', 'NIC'),
(129, 'Niger', 'NER'),
(130, 'Nigeria', 'NGA'),
(131, 'North Macedonia', 'MKD'),
(132, 'Norway', 'NOR'),
(133, 'Oman', 'OMN'),
(134, 'Pakistan', 'PAK'),
(135, 'Palau', 'PLW'),
(136, 'Panama', 'PAN'),
(137, 'Papua New Guinea', 'PNG'),
(138, 'Paraguay', 'PRY'),
(139, 'Peru', 'PER'),
(140, 'Philippines', 'PHL'),
(141, 'Poland', 'POL'),
(142, 'Portugal', 'PRT'),
(143, 'Qatar', 'QAT'),
(144, 'Romania', 'ROU'),
(145, 'Russia', 'RUS'),
(146, 'Rwanda', 'RWA'),
(147, 'Saint Kitts and Nevis', 'KNA'),
(148, 'Saint Lucia', 'LCA'),
(149, 'Saint Vincent and the Grenadines', 'VCT'),
(150, 'Samoa', 'WSM'),
(151, 'San Marino', 'SMR'),
(152, 'Sao Tome and Principe', 'STP'),
(153, 'Saudi Arabia', 'SAU'),
(154, 'Senegal', 'SEN'),
(155, 'Serbia', 'SRB'),
(156, 'Seychelles', 'SYC'),
(157, 'Sierra Leone', 'SLE'),
(158, 'Singapore', 'SGP'),
(159, 'Slovakia', 'SVK'),
(160, 'Slovenia', 'SVN'),
(161, 'Solomon Islands', 'SLB'),
(162, 'Somalia', 'SOM'),
(163, 'South Africa', 'ZAF'),
(164, 'Spain', 'ESP'),
(165, 'Sri Lanka', 'LKA'),
(166, 'Sudan', 'SDN'),
(167, 'Sudan, South', 'SSD'),
(168, 'Suriname', 'SUR'),
(169, 'Sweden', 'SWE'),
(170, 'Switzerland', 'CHE'),
(171, 'Syria', 'SYR'),
(172, 'Taiwan', 'TWN'),
(173, 'Tajikistan', 'TJK'),
(174, 'Tanzania', 'TZA'),
(175, 'Thailand', 'THA'),
(176, 'Togo', 'TGO'),
(177, 'Tonga', 'TON'),
(178, 'Trinidad and Tobago', 'TTO'),
(179, 'Tunisia', 'TUN'),
(180, 'Turkey', 'TUR'),
(181, 'Turkmenistan', 'TKM'),
(182, 'Tuvalu', 'TUV'),
(183, 'Uganda', 'UGA'),
(184, 'Ukraine', 'UKR'),
(185, 'United Arab Emirates', 'ARE'),
(186, 'United Kingdom', 'GBR'),
(187, 'United States', 'USA'),
(188, 'Uruguay', 'URY'),
(189, 'Uzbekistan', 'UZB'),
(190, 'Vanuatu', 'VUT'),
(191, 'Vatican City', 'VAT'),
(192, 'Venezuela', 'VEN'),
(193, 'Vietnam', 'VNM'),
(194, 'Yemen', 'YEM'),
(195, 'Zambia', 'ZMB'),
(196, 'Zimbabwe', 'ZWE');

INSERT INTO public."StudyLevel" (id, name) VALUES
(1, 'First year - Bachelor''s Degree'),
(2, 'Second year - Bachelor''s Degree'),
(3, 'Third year - Bachelor''s Degree'),
(4, 'First year - Master''s Degree'),
(5, 'Second year - Master''s Degree'),
(6, 'Doctorat - PhD');